### PR TITLE
Added possibility to view full story content without entering edit mode

### PR DESCRIPTION
**Pull request by sublibra**
Solved the issue where anonymous users couldn't see the whole story content. This is now possible with single click on story.

### CODE REVIEW

**Comment by fredriklindman** [comment]
I just committed another way of doing what I think you want. Feel free to try it on the stories in the story-task view: https://github.com/sonyxperiadev/BacklogTool/commit/02a304c6ea9754bf4d01ba780ded3d6814578a65
Untitled2

I can add the feature to the tasks, epics etc as well if it works as pleased.

**Comment by sublibra** [comment]
I'll pull and try this weekend. I have a similar solution (not pushed yet) where I replace the p.description text and resize the field when clicking on the ...

Your solution is probably cleaner but maybe we could use ... instead of [see all]?

**Comment by fredriklindman** [comment]
Sure we can use "..." to show more. What do you think we should have instead of "[hide extra]" in that case?

EDIT: I'm also thinking about trying to limit the number of rows instead of the number of characters before we truncate. For example if I have a description with a few characters on every line and have many lines, it does not get truncated. I'm not sure if that's a big problem in your production environment though?

**Comment by sublibra** [comment]
Hello,

I was thinking in these lines.
screenshot

I do like when the view as as clean as possible so ... appeals more than [more]. Maybe [min] is enough or leave the option out. As soon as a new story is created or reorder is made then the enlargement is lost.

The row count sounds like a good idea! Although the other issues/feature requests are of more importance in my mind. I only picked this one as a learning activity :)

Br
Jonas

**Comment by sublibra** [comment]
Ah.. Sloppy testing. You are right. Same issue goes for all task/theme etc. I'll fix.

**Comment by sublibra** [comment]
As discussed offline I have uploaded the current version with fixes for story, theme and epic but without support for expandable tasks. Maybe this can be used as a basis for the new expand whole story view. Use if you want.

**Comment by fredriklindman** [comment]
Thank you Jonas! Sorry, but I decided to go for the plugin approach after more consideration. Nevertheless it was a good source for inspiration! :) 

I have a question about the design for this change. I have tried to make it look like we discussed at our meeting, but still I'm not 100% sure of the design. From my point of view, the button for displaying full description can sometimes be mixed up with the button for displaying all tasks for the story. What do you guys think? Screenshot attached.
stories

EDIT: Another question: Do we want to collapse all extended descriptions when the user starts sorting stories?

**Comment by GLundh** [comment]
Damn. You are right. It looks clean and crisp, but it could certainly confuse some users.

While a "more"-button or clickable "..."  have some other weaknesses (like the user will not being able to use muscle memory to find the UI element), it surely is not as confusing.

**Comment by fredriklindman** [comment]
Okay, I can switch back to the three dots together with "[min]". Do you think it should be placed in the center of the whole story item as the arrow or should it be placed to the left below the text that's being extended? I think my vote goes for the left since it made sense to have an arrow in the middle, but not the dots.

It could also be placed in the last line that's being shown like in Jonas' change, but then it's a little harder to find the button since each every line does not end at the same location.

I'm also having in mind how the individual extend buttons in the view with titles only should look (if there should be any such buttons). If there should be such buttons in that view as well, then that change is tightly coupled with this change and I think we need another meeting before going any further with this.

**Pull request closed without merging**
