### PR TITLE
Fixes #41 Resolutions lower than 1680px

### PR DESCRIPTION
**Pull request by nilsi**
- Made more space for description
- Moved archived date to bottom right
- Made the layout look nice in 1024x768 resolution
- Refactoring code to look nicer.
- Other small UI changes

### CODE REVIEW

**Comment by fredriklindman** [comment]
Great, it's working perfectly in lower resolutions! Since it's good already, I will be very strict in my review.
1. I think the dynamic field select boxes should have a minimum width if possible. When I only have attributes with very few (or no) characters, they appear to be very thin.
2. The relative positioning of the dynamic fields are not the same in edit mode and in viewing mode - they appear to shuffle positions.
3. The positioning of elements like "customer","deadline" looks good for small windows, but when the window gets wider, I think they are too close to each other and there is lots of unused space to the right. Could that be streched with window size somehow?
4. It appears to not work as well in edit mode, see the picture below. Have you thought about this?
   screenshot from 2013-06-20 15 37 48

**Comment by nilsi** [comment]
1. Done. 70px min-width.
2. You mean that the prio selectbox are on the thirds row in edit view and on the second in non edit mode? Otherwise I dont see it here. I don't think really they are shuffled. More just like breaking new row. Can be that you running a different resolution.
3. I don't have this problem. I can't go higher than 1440 in resolution and I don't think it appears here or im blind.
4. Yes, Ive seen this. Its because it swaps to another layout at 1024. So when you are in between your resolution and 1024 it gets a bit strange. I changed this threshold to 1280x which makes it nicer on my computer but probably not as much on yours since you seems to have a higher resolution than that.

**Comment by fredriklindman** [comment]
1. Great :)
2. When in viewing mode, I read them as status->prio->effort (from left to right, then next row), but in edit mode they are aligned as status->effort->prio. Maybe it's just a matter of personal taste, I'm not sure.
3. Here is a screenshot. I think the statuses are too tight in relation to the space available to the right.
   screenshot from 2013-06-24 10 04 51
4. It looks better now but there are still some things to be fixed. The epic box jumps down quite quickly.
   Also, the label for the archive box lands in a totally different place sometimes:
   box

**Comment by nilsi** [comment]
1. It's because it breaks to a new row and when that happens it takes the element most to the right and add it to the new row which in this case are Prio. If people think's it's annoying we can spend some time trying to fix it but it requires some hours maybe, something that I dont think is worth to spend on it. Could do something like forcing three lines in non edit mode but then all stories gonna be higher.
2. It now changing the title and description fields width due to window size (more than before). Hope that helps. You seem to have a really high resolution compared to me. But I made my browser window double size of my screen and it seems to reduce the gap pretty much. Don't know why your contributor field is positioned further down though, something that I dont experience.
3. That should hopefully disappeared with 3.

Try it out and see if it's better. Gonna upload code shortly

**Pull request closed without merging**
